-- Seed data for 30 retro-futuristic products
-- Controlled tags: neural, interface, cyberpunk, featured, vintage, retro, ai, quantum, holographic, analog, digital, wireless, wired, portable, desktop, wearable, console, component, rare, common, restored, original, refurbished
-- Controlled eras: 1980s, 1990s, 2000s, 2010s, 2020s, 2030s, 2040s, 2045, 2050s
-- Controlled conditions: restored, original, refurbished, mint
-- Controlled rarities: rare, common, ultra-rare, limited

INSERT INTO products (product_id, sku, title, description, category, images, metadata, created_at, updated_at) VALUES
-- Neural Interfaces & Brain Tech
('pro_neural_v2_001', 'SKU-NI-V2-001', 'Neural Interface V2', 'Direct cortex connection device. Authentic 2045 model with quantum processing core. Restored to factory specifications with modern safety protocols.', 'hardware', '[]', '{"price": 299.99, "era": "2045", "isFeatured": true, "condition": "restored", "rarity": "rare", "brand": "NeuroTech", "story": "Recovered from a decommissioned research facility in Neo-Tokyo. This unit was part of the first commercial neural interface rollout before the Great Protocol Update of 2046.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 2045 | Recovered: 2052 | Restored: 2053", "origin": "Neo-Tokyo, Japan", "dimensions": "12cm × 8cm × 2cm", "weight": "180g", "warranty": "90 days restoration guarantee", "collectorNotes": "Rare early production model with original firmware intact", "energyRating": "A+", "compatibility": "Universal neural port standard", "attributes": {"connectivity": "wireless", "battery": "72h", "compatibility": "universal"}, "tags": ["neural", "interface", "cyberpunk", "featured"]}', strftime('%s','now'), strftime('%s','now')),

('pro_neural_mk1_002', 'SKU-NI-MK1-002', 'Neural Interface Mark I', 'First generation neural link from 2030s. Analog-digital hybrid with vintage aesthetic. Fully functional with period-accurate interface.', 'hardware', '[]', '{"price": 189.99, "era": "2030s", "isFeatured": false, "condition": "restored", "rarity": "rare", "brand": "NeuroTech", "story": "The original neural interface that started it all. This Mark I model predates the commercial rollout and was used in early research trials.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 2032 | Recovered: 2048 | Restored: 2050", "origin": "Silicon Valley, USA", "dimensions": "15cm × 10cm × 3cm", "weight": "220g", "warranty": "60 days restoration guarantee", "collectorNotes": "Historical significance - first commercial neural interface prototype", "energyRating": "B+", "compatibility": "Legacy neural port", "attributes": {"connectivity": "wired", "battery": "48h", "compatibility": "legacy"}, "tags": ["neural", "interface", "vintage", "retro"]}', strftime('%s','now'), strftime('%s','now')),

-- Retro Headphones & Audio
('pro_sony_mdr_003', 'SKU-SONY-MDR-003', 'Sony MDR-V6 Vintage', 'Classic 1980s studio monitor headphones. Unopened original packaging. Legendary sound quality that defined an era.', 'hardware', '[]', '{"price": 149.99, "era": "1980s", "isFeatured": true, "condition": "original", "rarity": "rare", "brand": "Sony", "story": "Found in a sealed warehouse in Tokyo. These headphones were never opened and represent the pinnacle of analog audio engineering.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 1985 | Discovered: 2048 | Status: Mint", "origin": "Tokyo, Japan", "dimensions": "28cm × 25cm × 12cm", "weight": "230g", "warranty": "30 days authenticity guarantee", "collectorNotes": "Unopened original box - extremely rare", "energyRating": "N/A", "compatibility": "3.5mm jack", "attributes": {"connectivity": "wired", "impedance": "63 ohms", "frequency": "5-30000 Hz"}, "tags": ["vintage", "audio", "headphones", "featured"]}', strftime('%s','now'), strftime('%s','now')),

('pro_akg_k240_004', 'SKU-AKG-K240-004', 'AKG K240 Studio', '1990s professional studio headphones. Restored to original specifications. Used by legendary producers of the era.', 'hardware', '[]', '{"price": 129.99, "era": "1990s", "isFeatured": false, "condition": "restored", "rarity": "common", "brand": "AKG", "story": "These headphones were used in major recording studios during the golden age of analog recording. Restored with original parts.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 1992 | Restored: 2051", "origin": "Vienna, Austria", "dimensions": "26cm × 24cm × 11cm", "weight": "240g", "warranty": "90 days restoration guarantee", "collectorNotes": "Professional studio grade - excellent condition", "energyRating": "N/A", "compatibility": "6.35mm jack", "attributes": {"connectivity": "wired", "impedance": "55 ohms", "frequency": "15-25000 Hz"}, "tags": ["vintage", "audio", "headphones", "studio"]}', strftime('%s','now'), strftime('%s','now')),

-- Retro Computers & Consoles
('pro_apple_ii_005', 'SKU-APPLE-II-005', 'Apple IIe Computer', 'Classic 1980s personal computer. Fully functional with original software. The machine that started the personal computing revolution.', 'console', '[]', '{"price": 899.99, "era": "1980s", "isFeatured": true, "condition": "restored", "rarity": "rare", "brand": "Apple", "story": "This Apple IIe was used in a small business for over 20 years before being preserved. Complete with original manuals and software.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 1983 | Restored: 2049", "origin": "Cupertino, USA", "dimensions": "38cm × 48cm × 11cm", "weight": "5.2kg", "warranty": "90 days restoration guarantee", "collectorNotes": "Complete system with monitor and peripherals", "energyRating": "C", "compatibility": "Original Apple II peripherals", "attributes": {"cpu": "6502", "ram": "64KB", "storage": "5.25 floppy"}, "tags": ["vintage", "computer", "retro", "featured", "console"]}', strftime('%s','now'), strftime('%s','now')),

('pro_commodore_64_006', 'SKU-COM-64-006', 'Commodore 64', 'Iconic 1980s home computer. Restored with original keyboard and power supply. Includes period-accurate games collection.', 'console', '[]', '{"price": 349.99, "era": "1980s", "isFeatured": false, "condition": "restored", "rarity": "common", "brand": "Commodore", "story": "The best-selling single computer model of all time. This unit was carefully restored to preserve its original character.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 1982 | Restored: 2050", "origin": "West Chester, USA", "dimensions": "40cm × 20cm × 7cm", "weight": "1.8kg", "warranty": "90 days restoration guarantee", "collectorNotes": "Includes original box and documentation", "energyRating": "C", "compatibility": "Commodore peripherals", "attributes": {"cpu": "6510", "ram": "64KB", "storage": "Datasette"}, "tags": ["vintage", "computer", "retro", "console"]}', strftime('%s','now'), strftime('%s','now')),

('pro_gameboy_007', 'SKU-NIN-GB-007', 'Nintendo Game Boy Original', '1989 original Game Boy. Unopened mint condition. The handheld that changed gaming forever.', 'console', '[]', '{"price": 249.99, "era": "1980s", "isFeatured": true, "condition": "original", "rarity": "rare", "brand": "Nintendo", "story": "Sealed in original packaging. This Game Boy was never used and represents a perfect time capsule of 1989 gaming technology.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 1989 | Status: Mint Unopened", "origin": "Kyoto, Japan", "dimensions": "9cm × 15cm × 3cm", "weight": "220g", "warranty": "30 days authenticity guarantee", "collectorNotes": "Unopened original packaging - museum quality", "energyRating": "N/A", "compatibility": "Game Boy cartridges", "attributes": {"screen": "160x144 monochrome", "battery": "4x AA", "processor": "Sharp LR35902"}, "tags": ["vintage", "gaming", "portable", "featured", "console"]}', strftime('%s','now'), strftime('%s','now')),

-- AI & Quantum Devices
('pro_rabbit_r1_008', 'SKU-RAB-R1-008', 'Rabbit R1 AI Assistant', '2024 revolutionary AI device. Unopened original. The device that redefined human-AI interaction.', 'hardware', '[]', '{"price": 199.99, "era": "2020s", "isFeatured": true, "condition": "original", "rarity": "rare", "brand": "Rabbit", "story": "The Rabbit R1 was a breakthrough in AI hardware design. This unopened unit represents the beginning of the AI assistant era.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 2024 | Status: Mint Unopened", "origin": "San Francisco, USA", "dimensions": "8cm × 8cm × 1.5cm", "weight": "115g", "warranty": "30 days authenticity guarantee", "collectorNotes": "Sealed original packaging - early production model", "energyRating": "A", "compatibility": "Universal AI protocols", "attributes": {"connectivity": "wireless", "battery": "All day", "ai": "Large Action Model"}, "tags": ["ai", "assistant", "portable", "featured", "wireless"]}', strftime('%s','now'), strftime('%s','now')),

('pro_quantum_pad_009', 'SKU-QP-PAD-009', 'Quantum Processing Pad', '2040s quantum computing tablet. Restored with original quantum core intact. Capable of parallel universe calculations.', 'hardware', '[]', '{"price": 1299.99, "era": "2040s", "isFeatured": true, "condition": "restored", "rarity": "ultra-rare", "brand": "QuantumTech", "story": "Recovered from a quantum research lab. This device can process calculations across multiple quantum states simultaneously.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 2042 | Recovered: 2050 | Restored: 2052", "origin": "CERN, Switzerland", "dimensions": "25cm × 18cm × 0.8cm", "weight": "450g", "warranty": "90 days restoration guarantee", "collectorNotes": "Functional quantum processor - extremely rare", "energyRating": "A++", "compatibility": "Quantum network protocols", "attributes": {"connectivity": "quantum wireless", "battery": "72h", "qubits": "1024"}, "tags": ["quantum", "computing", "cyberpunk", "featured", "ultra-rare"]}', strftime('%s','now'), strftime('%s','now')),

-- Holographic Displays
('pro_holo_display_010', 'SKU-HOLO-DISP-010', 'Holographic Display Cube', '2030s 3D holographic display. Projects full-color 3D images in mid-air. Restored to original specifications.', 'hardware', '[]', '{"price": 599.99, "era": "2030s", "isFeatured": false, "condition": "restored", "rarity": "rare", "brand": "HoloTech", "story": "Early commercial holographic display technology. This cube was used in corporate presentations and represents cutting-edge 2030s tech.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 2035 | Restored: 2049", "origin": "Seoul, South Korea", "dimensions": "20cm × 20cm × 20cm", "weight": "1.2kg", "warranty": "90 days restoration guarantee", "collectorNotes": "Fully functional holographic projection", "energyRating": "B+", "compatibility": "USB-C, wireless", "attributes": {"connectivity": "wireless", "battery": "4h", "resolution": "4K holographic"}, "tags": ["holographic", "display", "3d", "cyberpunk"]}', strftime('%s','now'), strftime('%s','now')),

-- Retro Cameras
('pro_polaroid_600_011', 'SKU-POL-600-011', 'Polaroid 600 Camera', '1980s instant camera. Unopened original box. The camera that made instant photography accessible.', 'hardware', '[]', '{"price": 179.99, "era": "1980s", "isFeatured": false, "condition": "original", "rarity": "common", "brand": "Polaroid", "story": "The Polaroid 600 was the most popular instant camera of its era. This unopened unit is a perfect time capsule.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 1981 | Status: Mint Unopened", "origin": "Cambridge, USA", "dimensions": "16cm × 11cm × 10cm", "weight": "650g", "warranty": "30 days authenticity guarantee", "collectorNotes": "Original packaging with film included", "energyRating": "N/A", "compatibility": "Polaroid 600 film", "attributes": {"film": "600 type", "flash": "Built-in", "focus": "Fixed"}, "tags": ["vintage", "camera", "photography", "retro"]}', strftime('%s','now'), strftime('%s','now')),

-- Vintage Keyboards
('pro_ibm_model_m_012', 'SKU-IBM-M-M-012', 'IBM Model M Keyboard', '1980s mechanical keyboard. The legendary clicky keyboard. Restored with original buckling spring switches.', 'component', '[]', '{"price": 199.99, "era": "1980s", "isFeatured": true, "condition": "restored", "rarity": "rare", "brand": "IBM", "story": "The IBM Model M is considered by many to be the greatest keyboard ever made. This unit has been carefully restored.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 1986 | Restored: 2048", "origin": "Lexington, USA", "dimensions": "50cm × 20cm × 4cm", "weight": "1.4kg", "warranty": "90 days restoration guarantee", "collectorNotes": "Original buckling spring switches - legendary feel", "energyRating": "N/A", "compatibility": "PS/2, USB adapter included", "attributes": {"switches": "Buckling spring", "layout": "Full size", "connection": "PS/2"}, "tags": ["vintage", "keyboard", "mechanical", "featured", "component"]}', strftime('%s','now'), strftime('%s','now')),

-- Retro Gaming
('pro_atari_2600_013', 'SKU-ATA-2600-013', 'Atari 2600 Console', '1970s-1980s home video game console. Restored with original controllers and game cartridges.', 'console', '[]', '{"price": 299.99, "era": "1980s", "isFeatured": false, "condition": "restored", "rarity": "common", "brand": "Atari", "story": "The console that started the home video game revolution. This unit includes 10 classic game cartridges.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 1977 | Restored: 2047", "origin": "Sunnyvale, USA", "dimensions": "40cm × 30cm × 8cm", "weight": "1.2kg", "warranty": "90 days restoration guarantee", "collectorNotes": "Includes original joystick controllers", "energyRating": "D", "compatibility": "Atari 2600 cartridges", "attributes": {"cpu": "6507", "ram": "128 bytes", "graphics": "TIA chip"}, "tags": ["vintage", "gaming", "retro", "console"]}', strftime('%s','now'), strftime('%s','now')),

-- AI Companions
('pro_ai_pet_014', 'SKU-AI-PET-014', 'AI Companion Pet', '2020s AI-powered robotic pet. Unopened original. Learns and evolves with interaction. The future of companionship.', 'hardware', '[]', '{"price": 399.99, "era": "2020s", "isFeatured": false, "condition": "original", "rarity": "rare", "brand": "TechPets", "story": "Early AI companion technology that could learn and adapt. This unopened unit represents the beginning of emotional AI.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 2023 | Status: Mint Unopened", "origin": "Boston, USA", "dimensions": "25cm × 20cm × 15cm", "weight": "800g", "warranty": "30 days authenticity guarantee", "collectorNotes": "Sealed original packaging", "energyRating": "A", "compatibility": "Wireless charging", "attributes": {"connectivity": "wireless", "battery": "8h active", "ai": "Machine learning"}, "tags": ["ai", "companion", "robotic", "wireless"]}', strftime('%s','now'), strftime('%s','now')),

-- Vintage Calculators
('pro_hp_calc_015', 'SKU-HP-CALC-015', 'HP-12C Financial Calculator', '1980s programmable financial calculator. Still used by professionals today. Mint condition.', 'component', '[]', '{"price": 89.99, "era": "1980s", "isFeatured": false, "condition": "mint", "rarity": "common", "brand": "Hewlett-Packard", "story": "The HP-12C is still in production today, a testament to its design. This vintage model has the original RPN logic.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 1981 | Status: Mint", "origin": "Corvallis, USA", "dimensions": "13cm × 8cm × 1.5cm", "weight": "120g", "warranty": "30 days authenticity guarantee", "collectorNotes": "Original packaging and manual", "energyRating": "N/A", "compatibility": "Battery powered", "attributes": {"display": "LCD", "battery": "3x button cell", "logic": "RPN"}, "tags": ["vintage", "calculator", "component"]}', strftime('%s','now'), strftime('%s','now')),

-- Cyberpunk Wearables
('pro_cyber_glove_016', 'SKU-CYB-GLOVE-016', 'Cyberpunk Data Glove', '2040s haptic feedback data glove. Allows direct manipulation of digital objects. Restored with original sensors.', 'wearable', '[]', '{"price": 449.99, "era": "2040s", "isFeatured": true, "condition": "restored", "rarity": "rare", "brand": "CyberWear", "story": "Early haptic interface technology. This glove was used in virtual reality research and represents cutting-edge 2040s tech.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 2041 | Restored: 2051", "origin": "Singapore", "dimensions": "Fits all sizes", "weight": "180g", "warranty": "90 days restoration guarantee", "collectorNotes": "Fully functional haptic sensors", "energyRating": "A", "compatibility": "Wireless VR systems", "attributes": {"connectivity": "wireless", "battery": "12h", "sensors": "20 haptic points"}, "tags": ["cyberpunk", "wearable", "haptic", "featured", "wireless"]}', strftime('%s','now'), strftime('%s','now')),

-- Retro Radios
('pro_zenith_trans_017', 'SKU-ZEN-TRANS-017', 'Zenith Trans-Oceanic Radio', '1960s-1970s portable shortwave radio. Restored to original specifications. The ultimate portable radio of its era.', 'hardware', '[]', '{"price": 279.99, "era": "1970s", "isFeatured": false, "condition": "restored", "rarity": "rare", "brand": "Zenith", "story": "The Trans-Oceanic was the premium portable radio of its time. This restored unit can still pick up signals from around the world.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 1970 | Restored: 2048", "origin": "Chicago, USA", "dimensions": "35cm × 20cm × 12cm", "weight": "3.5kg", "warranty": "90 days restoration guarantee", "collectorNotes": "Fully functional shortwave receiver", "energyRating": "D", "compatibility": "Battery or AC", "attributes": {"bands": "AM/FM/Shortwave", "battery": "9x D cell", "tubes": "Vacuum tube"}, "tags": ["vintage", "radio", "retro"]}', strftime('%s','now'), strftime('%s','now')),

-- Quantum Storage
('pro_quantum_drive_018', 'SKU-QD-DRIVE-018', 'Quantum Storage Drive', '2045 quantum data storage device. Stores data in quantum states. Capable of holding petabytes in a small form factor.', 'component', '[]', '{"price": 799.99, "era": "2045", "isFeatured": false, "condition": "restored", "rarity": "ultra-rare", "brand": "QuantumStorage", "story": "Early quantum storage technology. This drive can store massive amounts of data using quantum superposition states.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 2045 | Recovered: 2050 | Restored: 2052", "origin": "Zurich, Switzerland", "dimensions": "10cm × 7cm × 1cm", "weight": "85g", "warranty": "90 days restoration guarantee", "collectorNotes": "Functional quantum storage - extremely rare", "energyRating": "A+", "compatibility": "Quantum interface", "attributes": {"capacity": "10PB", "interface": "quantum", "speed": "Instant access"}, "tags": ["quantum", "storage", "cyberpunk", "ultra-rare", "component"]}', strftime('%s','now'), strftime('%s','now')),

-- Retro Typewriters
('pro_olivetti_019', 'SKU-OLI-LET-019', 'Olivetti Lettera 32', '1960s portable typewriter. Restored with original ribbon mechanism. The writer''s tool of choice for decades.', 'hardware', '[]', '{"price": 229.99, "era": "1960s", "isFeatured": false, "condition": "restored", "rarity": "common", "brand": "Olivetti", "story": "The Lettera 32 was one of the most popular portable typewriters ever made. This restored unit types like new.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 1963 | Restored: 2047", "origin": "Ivrea, Italy", "dimensions": "33cm × 35cm × 10cm", "weight": "4.2kg", "warranty": "90 days restoration guarantee", "collectorNotes": "Fully functional with original mechanism", "energyRating": "N/A", "compatibility": "Standard typewriter ribbon", "attributes": {"keys": "44 keys", "ribbon": "Standard", "carriage": "Manual return"}, "tags": ["vintage", "typewriter", "retro"]}', strftime('%s','now'), strftime('%s','now')),

-- AI Art Generator
('pro_ai_art_020', 'SKU-AI-ART-020', 'AI Art Generator Station', '2030s standalone AI art creation device. Creates original artwork using neural networks. Restored with original AI models.', 'hardware', '[]', '{"price": 549.99, "era": "2030s", "isFeatured": false, "condition": "restored", "rarity": "rare", "brand": "ArtAI", "story": "Early AI art generation technology. This device can create original artwork using trained neural networks.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 2034 | Restored: 2049", "origin": "London, UK", "dimensions": "30cm × 25cm × 5cm", "weight": "1.8kg", "warranty": "90 days restoration guarantee", "collectorNotes": "Includes original AI model library", "energyRating": "B+", "compatibility": "USB-C, wireless", "attributes": {"connectivity": "wireless", "battery": "6h", "ai": "Neural network"}, "tags": ["ai", "art", "creative", "cyberpunk"]}', strftime('%s','now'), strftime('%s','now')),

-- Vintage Walkman
('pro_sony_walkman_021', 'SKU-SONY-WM-021', 'Sony Walkman TPS-L2', '1979 original Walkman. The device that made portable music personal. Unopened mint condition.', 'hardware', '[]', '{"price": 399.99, "era": "1980s", "isFeatured": true, "condition": "original", "rarity": "ultra-rare", "brand": "Sony", "story": "The very first Walkman model. This unopened unit is a holy grail for collectors. The device that changed how we listen to music.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 1979 | Status: Mint Unopened", "origin": "Tokyo, Japan", "dimensions": "13cm × 9cm × 3cm", "weight": "390g", "warranty": "30 days authenticity guarantee", "collectorNotes": "First generation Walkman - museum quality", "energyRating": "N/A", "compatibility": "Cassette tapes", "attributes": {"format": "Cassette", "battery": "2x AA", "headphones": "MDR-3L2"}, "tags": ["vintage", "audio", "portable", "featured", "ultra-rare"]}', strftime('%s','now'), strftime('%s','now')),

-- Cyberpunk VR Headset
('pro_vr_cyber_022', 'SKU-VR-CYB-022', 'Cyberpunk VR Headset', '2040s full-immersion VR headset. Neural link compatible. Restored with original haptic feedback systems.', 'wearable', '[]', '{"price": 899.99, "era": "2040s", "isFeatured": true, "condition": "restored", "rarity": "rare", "brand": "VRSystems", "story": "Cutting-edge VR technology from the 2040s. This headset provides full neural integration for complete immersion.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 2043 | Restored: 2051", "origin": "Seoul, South Korea", "dimensions": "25cm × 20cm × 15cm", "weight": "650g", "warranty": "90 days restoration guarantee", "collectorNotes": "Neural link compatible - fully functional", "energyRating": "A", "compatibility": "Neural interfaces", "attributes": {"connectivity": "wireless", "battery": "8h", "resolution": "8K per eye"}, "tags": ["cyberpunk", "vr", "wearable", "featured", "neural"]}', strftime('%s','now'), strftime('%s','now')),

-- Retro PDA
('pro_palm_pilot_023', 'SKU-PALM-PIL-023', 'Palm Pilot Professional', '1990s personal digital assistant. The smartphone before smartphones. Restored with original software.', 'hardware', '[]', '{"price": 149.99, "era": "1990s", "isFeatured": false, "condition": "restored", "rarity": "common", "brand": "Palm", "story": "The Palm Pilot was the first successful PDA. This restored unit includes original applications and sync software.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 1997 | Restored: 2048", "origin": "Santa Clara, USA", "dimensions": "12cm × 8cm × 1.5cm", "weight": "160g", "warranty": "90 days restoration guarantee", "collectorNotes": "Includes original stylus and software", "energyRating": "N/A", "compatibility": "Palm sync cable", "attributes": {"display": "Monochrome LCD", "memory": "1MB", "os": "Palm OS"}, "tags": ["vintage", "pda", "retro"]}', strftime('%s','now'), strftime('%s','now')),

-- Quantum Watch
('pro_quantum_watch_024', 'SKU-QW-WATCH-024', 'Quantum Timepiece', '2045 quantum-powered watch. Displays time across multiple dimensions. Restored with original quantum core.', 'wearable', '[]', '{"price": 1299.99, "era": "2045", "isFeatured": true, "condition": "restored", "rarity": "ultra-rare", "brand": "QuantumTime", "story": "Experimental quantum timepiece that can theoretically display time from parallel dimensions. Recovered from quantum research facility.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 2045 | Recovered: 2050 | Restored: 2053", "origin": "CERN, Switzerland", "dimensions": "4cm × 4cm × 1cm", "weight": "85g", "warranty": "90 days restoration guarantee", "collectorNotes": "Functional quantum time display - extremely rare", "energyRating": "A++", "compatibility": "Quantum network", "attributes": {"connectivity": "quantum wireless", "battery": "Perpetual", "display": "Quantum holographic"}, "tags": ["quantum", "watch", "wearable", "featured", "ultra-rare", "cyberpunk"]}', strftime('%s','now'), strftime('%s','now')),

-- Retro Synthesizer
('pro_moog_synth_025', 'SKU-MOO-SYN-025', 'Moog Minimoog', '1970s analog synthesizer. The legendary synth that defined electronic music. Restored with original oscillators.', 'hardware', '[]', '{"price": 2499.99, "era": "1970s", "isFeatured": true, "condition": "restored", "rarity": "rare", "brand": "Moog", "story": "The Minimoog is one of the most iconic synthesizers ever made. This restored unit has been used by legendary musicians.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 1971 | Restored: 2046", "origin": "Trumansburg, USA", "dimensions": "60cm × 30cm × 15cm", "weight": "13kg", "warranty": "90 days restoration guarantee", "collectorNotes": "Original oscillators and filters - legendary sound", "energyRating": "N/A", "compatibility": "CV/Gate, MIDI", "attributes": {"oscillators": "3 VCOs", "filter": "24dB/octave", "keys": "44 keys"}, "tags": ["vintage", "synthesizer", "audio", "featured", "retro"]}', strftime('%s','now'), strftime('%s','now')),

-- AI Translator
('pro_ai_trans_026', 'SKU-AI-TRANS-026', 'Universal AI Translator', '2030s real-time translation device. Translates any language instantly using AI. Restored with original language models.', 'hardware', '[]', '{"price": 349.99, "era": "2030s", "isFeatured": false, "condition": "restored", "rarity": "common", "brand": "LinguaTech", "story": "Early AI translation technology that could translate between any languages in real-time. This restored unit includes 200+ language models.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 2032 | Restored: 2048", "origin": "San Francisco, USA", "dimensions": "10cm × 6cm × 1cm", "weight": "120g", "warranty": "90 days restoration guarantee", "collectorNotes": "Includes original language database", "energyRating": "A", "compatibility": "Wireless, USB-C", "attributes": {"connectivity": "wireless", "battery": "12h", "languages": "200+"}, "tags": ["ai", "translation", "portable", "wireless"]}', strftime('%s','now'), strftime('%s','now')),

-- Vintage Computer Monitor
('pro_crt_monitor_027', 'SKU-CRT-MON-027', 'Sony Trinitron CRT Monitor', '1990s professional CRT monitor. The gold standard for color accuracy. Restored with original tube.', 'component', '[]', '{"price": 179.99, "era": "1990s", "isFeatured": false, "condition": "restored", "rarity": "common", "brand": "Sony", "story": "The Trinitron was the professional monitor of choice for decades. This restored unit maintains perfect color accuracy.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 1995 | Restored: 2047", "origin": "Tokyo, Japan", "dimensions": "45cm × 40cm × 45cm", "weight": "18kg", "warranty": "90 days restoration guarantee", "collectorNotes": "Original Trinitron tube - excellent condition", "energyRating": "D", "compatibility": "VGA, DVI", "attributes": {"size": "21 inch", "resolution": "1600x1200", "tube": "Trinitron"}, "tags": ["vintage", "monitor", "component", "retro"]}', strftime('%s','now'), strftime('%s','now')),

-- Cyberpunk Implant
('pro_cyber_implant_028', 'SKU-CYB-IMP-028', 'Neural Data Implant', '2045 neural data interface implant. Allows direct brain-computer interface. Display model (non-functional).', 'component', '[]', '{"price": 599.99, "era": "2045", "isFeatured": false, "condition": "original", "rarity": "ultra-rare", "brand": "NeuroLink", "story": "Early neural implant technology. This display model shows the actual implant design used in early human trials. Non-functional display piece.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 2045 | Status: Display Model", "origin": "Neo-Tokyo, Japan", "dimensions": "2cm × 1cm × 0.5cm", "weight": "5g", "warranty": "30 days authenticity guarantee", "collectorNotes": "Display model - non-functional but authentic design", "energyRating": "N/A", "compatibility": "Neural interface", "attributes": {"type": "Display model", "material": "Medical grade", "interface": "Neural"}, "tags": ["cyberpunk", "neural", "implant", "ultra-rare", "component"]}', strftime('%s','now'), strftime('%s','now')),

-- Retro Floppy Drive
('pro_floppy_drive_029', 'SKU-FLO-DRIVE-029', '5.25" Floppy Drive', '1980s external floppy disk drive. Restored with original mechanism. For vintage computer enthusiasts.', 'component', '[]', '{"price": 79.99, "era": "1980s", "isFeatured": false, "condition": "restored", "rarity": "common", "brand": "Generic", "story": "Standard 5.25 inch floppy drive from the 1980s. Essential for vintage computer systems. Fully restored and tested.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 1983 | Restored: 2048", "origin": "Various", "dimensions": "15cm × 20cm × 6cm", "weight": "1.2kg", "warranty": "90 days restoration guarantee", "collectorNotes": "Fully functional with original mechanism", "energyRating": "N/A", "compatibility": "5.25 floppy disks", "attributes": {"capacity": "360KB", "interface": "Parallel", "format": "5.25 inch"}, "tags": ["vintage", "storage", "component", "retro"]}', strftime('%s','now'), strftime('%s','now')),

-- AI Home Assistant
('pro_ai_home_030', 'SKU-AI-HOME-030', 'AI Home Control Hub', '2020s smart home AI controller. Unopened original. Controls entire home with voice commands. The future of home automation.', 'hardware', '[]', '{"price": 249.99, "era": "2020s", "isFeatured": false, "condition": "original", "rarity": "common", "brand": "HomeAI", "story": "Early smart home AI technology. This unopened unit represents the beginning of intelligent home automation.", "certification": "Authenticated by CyberVintage Labs", "timeline": "Manufactured: 2022 | Status: Mint Unopened", "origin": "Seattle, USA", "dimensions": "15cm × 15cm × 5cm", "weight": "450g", "warranty": "30 days authenticity guarantee", "collectorNotes": "Sealed original packaging", "energyRating": "A", "compatibility": "WiFi, Zigbee, Z-Wave", "attributes": {"connectivity": "wireless", "power": "AC adapter", "ai": "Voice assistant"}, "tags": ["ai", "smart home", "automation", "wireless"]}', strftime('%s','now'), strftime('%s','now'));
